name: narrativa

require:
  - bolt

pipeline:
  - mecha

data_pack:
  load:
    - src

resource_pack:
  load:
    - src

output: build

meta:
  bolt:
    entrypoint: [
      "ceevyte:narrativa",

      "example:dialog",
      "example:choice",
      "example:handler",



      "example:trees/lorem_ipsum"
    ]