name: narrativa

require:
  - bolt

pipeline:
  - mecha

data_pack:
  load:
    - src

resource_pack:
  load:
    - src

output: build

meta:
  bolt:
    entrypoint: [
      "ceevyte:narrativa",

      "username:example/narrativa/handler",
      "username:example/narrativa/trees/dialog_tree_example",

      "username:finish"
    ]