name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Code
        uses: [actions/checkout](https://github.com)@v4

      - name: Zip Repository
        run: zip -r release.zip . -x "*.git*"

      - name: Create and Upload Release
        uses: [ncipollo/release-action](https://github.com)@v1
        with:
          artifacts: "release.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
          generateReleaseNotes: true
