name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Zip repository (excluding build folder)
        run: zip -r release.zip . --exclude "./build/*"

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12.3'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Build
        run: beet build

      - name: Zip build folder
        run: |
          cd build/narrativa_data_pack
          cp -r ../narrativa_resource_pack/assets .
          zip -r ../../build.zip .

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            release.zip
            build.zip